{"updated_at": "2012-12-03T22:46:10Z", "repo": "rails", "created_at": "2012-12-03T22:46:10Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/10975902", "id": 10975902, "issue_url": "https://api.github.com/repos/rails/rails/issues/3524", "issue_id": 3524, "user": {"repos_url": "https://api.github.com/users/geopet/repos", "type": "User", "html_url": "https://github.com/geopet", "starred_url": "https://api.github.com/users/geopet/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/geopet/subscriptions", "following_url": "https://api.github.com/users/geopet/following{/other_user}", "gravatar_id": "71e5c7e9a86b98fc12a880450762d9d5", "organizations_url": "https://api.github.com/users/geopet/orgs", "url": "https://api.github.com/users/geopet", "gists_url": "https://api.github.com/users/geopet/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/71e5c7e9a86b98fc12a880450762d9d5?d=https%3A%2F%2Fidenticons.github.com%2Fc437b36ac74d2e33ae8f39388b47f3a3.png", "id": 632827, "events_url": "https://api.github.com/users/geopet/events{/privacy}", "login": "geopet", "received_events_url": "https://api.github.com/users/geopet/received_events", "followers_url": "https://api.github.com/users/geopet/followers"}, "body": "I'm just following up with another ping as well. Should this be kept open? Is this still an issue?", "_id": {"$oid": "5238356fbd3543c15100fc49"}, "html_url": "https://github.com/rails/rails/pull/3524#issuecomment-10975902"}
