{"updated_at": "2013-03-27T15:58:39Z", "repo": "rails", "created_at": "2013-03-27T15:58:39Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/15532200", "id": 15532200, "issue_url": "https://api.github.com/repos/rails/rails/issues/9898", "issue_id": 9898, "user": {"repos_url": "https://api.github.com/users/rafaelfranca/repos", "type": "User", "html_url": "https://github.com/rafaelfranca", "starred_url": "https://api.github.com/users/rafaelfranca/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rafaelfranca/subscriptions", "following_url": "https://api.github.com/users/rafaelfranca/following{/other_user}", "gravatar_id": "0525b332aafb83307b32d9747a93de03", "organizations_url": "https://api.github.com/users/rafaelfranca/orgs", "url": "https://api.github.com/users/rafaelfranca", "gists_url": "https://api.github.com/users/rafaelfranca/gists{/gist_id}", "avatar_url": "https://1.gravatar.com/avatar/0525b332aafb83307b32d9747a93de03?d=https%3A%2F%2Fidenticons.github.com%2F2c7b84fa30f0cea96a90729afe2970a0.png", "id": 47848, "events_url": "https://api.github.com/users/rafaelfranca/events{/privacy}", "login": "rafaelfranca", "received_events_url": "https://api.github.com/users/rafaelfranca/received_events", "followers_url": "https://api.github.com/users/rafaelfranca/followers"}, "body": "I think is not a good idea to be defensive like this. We really don't need to change the code to check if one argument is a unexpected value.\r\n\r\nI think is better to try to reproduce in a new application and fix the real cause of this issue.", "_id": {"$oid": "5237e5b9bd3543c1510093c4"}, "html_url": "https://github.com/rails/rails/pull/9898#issuecomment-15532200"}
