{"issue_url": "https://api.github.com/repos/rails/rails/issues/11626", "repo": "rails", "body": "As documented in thread you linked:\r\n\r\n```ruby\r\ne = assert_raises ArgumentError do\r\n  dc = Dalli::Client.new('localhost', :badopt => true)\r\nend\r\n\r\nassert_match(/Unsupported option/, e.message) # or assert_equal etc... also allows testing attribs\r\n```\r\n\r\nI agree with @steveklabnik that it's better not to assert on the message if possible. If you have to, use the exception returned by `assert_raises`.", "_id": {"$oid": "5237d2adbd3543c151007ea9"}, "issue_id": 11626, "url": "https://api.github.com/repos/rails/rails/issues/comments/21715900", "html_url": "https://github.com/rails/rails/pull/11626#issuecomment-21715900", "updated_at": "2013-07-29T12:18:37Z", "user": {"subscriptions_url": "https://api.github.com/users/senny/subscriptions", "events_url": "https://api.github.com/users/senny/events{/privacy}", "repos_url": "https://api.github.com/users/senny/repos", "gists_url": "https://api.github.com/users/senny/gists{/gist_id}", "url": "https://api.github.com/users/senny", "login": "senny", "gravatar_id": "3d698e2872c07061a455d9e250861235", "html_url": "https://github.com/senny", "following_url": "https://api.github.com/users/senny/following{/other_user}", "received_events_url": "https://api.github.com/users/senny/received_events", "organizations_url": "https://api.github.com/users/senny/orgs", "avatar_url": "https://1.gravatar.com/avatar/3d698e2872c07061a455d9e250861235?d=https%3A%2F%2Fidenticons.github.com%2Fd1359f9934ee5a75ed441ffce412a0a1.png", "starred_url": "https://api.github.com/users/senny/starred{/owner}{/repo}", "id": 5402, "followers_url": "https://api.github.com/users/senny/followers", "type": "User"}, "created_at": "2013-07-29T12:18:37Z", "id": 21715900, "owner": "rails"}
