{"body": "did the tests, but (dont know why), the other tests are getting errors like \"stack too deep\", maybe i did forgot to do something prior to test preparation. but was not my fault, cant execute the aggregation tests on HEAD/rails too.\r\n\r\nanyway, the tests for the delegate and methods are working.", "url": "https://api.github.com/repos/rails/rails/issues/comments/2961620", "created_at": "2011-11-30T16:02:10Z", "html_url": "https://github.com/rails/rails/pull/3807#issuecomment-2961620", "updated_at": "2011-11-30T16:02:10Z", "repo": "rails", "issue_id": 3807, "user": {"following_url": "https://api.github.com/users/pnegri/following{/other_user}", "events_url": "https://api.github.com/users/pnegri/events{/privacy}", "organizations_url": "https://api.github.com/users/pnegri/orgs", "url": "https://api.github.com/users/pnegri", "gists_url": "https://api.github.com/users/pnegri/gists{/gist_id}", "html_url": "https://github.com/pnegri", "subscriptions_url": "https://api.github.com/users/pnegri/subscriptions", "avatar_url": "https://0.gravatar.com/avatar/88c091b3d0f88ba1c626fa45df590e00?d=https%3A%2F%2Fidenticons.github.com%2Fbb98e37f40dc9e68732cb12cb785a772.png", "repos_url": "https://api.github.com/users/pnegri/repos", "received_events_url": "https://api.github.com/users/pnegri/received_events", "gravatar_id": "88c091b3d0f88ba1c626fa45df590e00", "starred_url": "https://api.github.com/users/pnegri/starred{/owner}{/repo}", "login": "pnegri", "type": "User", "id": 39310, "followers_url": "https://api.github.com/users/pnegri/followers"}, "owner": "rails", "_id": {"$oid": "52383159bd3543c15100f737"}, "id": 2961620, "issue_url": "https://api.github.com/repos/rails/rails/issues/3807"}
