{"updated_at": "2012-05-16T02:04:17Z", "repo": "rails", "created_at": "2012-05-16T02:04:17Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/5732085", "id": 5732085, "issue_url": "https://api.github.com/repos/rails/rails/issues/6332", "issue_id": 6332, "user": {"repos_url": "https://api.github.com/users/mpapis/repos", "type": "User", "html_url": "https://github.com/mpapis", "starred_url": "https://api.github.com/users/mpapis/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mpapis/subscriptions", "following_url": "https://api.github.com/users/mpapis/following{/other_user}", "gravatar_id": "3ec52ed58eb92026d86e62c39bdb7589", "organizations_url": "https://api.github.com/users/mpapis/orgs", "url": "https://api.github.com/users/mpapis", "gists_url": "https://api.github.com/users/mpapis/gists{/gist_id}", "avatar_url": "https://0.gravatar.com/avatar/3ec52ed58eb92026d86e62c39bdb7589?d=https%3A%2F%2Fidenticons.github.com%2F88265682f64ddb514c09888a3a37c511.png", "id": 48054, "events_url": "https://api.github.com/users/mpapis/events{/privacy}", "login": "mpapis", "received_events_url": "https://api.github.com/users/mpapis/received_events", "followers_url": "https://api.github.com/users/mpapis/followers"}, "body": "`bundle exec` is no fun in this case, we have two conflicting Gemfiles:\n\n- one from rails\n- second from the plugin test\n\nAnd only the second should be loaded during this exact test - which will be assured by my fix in #6318, the issue here is that the test was running before in context of the first Gemfile instead of second - now I have added additional tests to check `#{destination_root}/Gemfile.lock` which validates `bundle install` was run in proper context.\n", "_id": {"$oid": "52380b55bd3543c15100cff1"}, "html_url": "https://github.com/rails/rails/pull/6332#issuecomment-5732085"}
