{"updated_at": "2012-06-02T18:47:45Z", "repo": "rails", "created_at": "2012-06-02T18:47:45Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/6079799", "id": 6079799, "issue_url": "https://api.github.com/repos/rails/rails/issues/5396", "issue_id": 5396, "user": {"repos_url": "https://api.github.com/users/sausman/repos", "type": "User", "html_url": "https://github.com/sausman", "starred_url": "https://api.github.com/users/sausman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sausman/subscriptions", "following_url": "https://api.github.com/users/sausman/following{/other_user}", "gravatar_id": "03bcc4174eb7d5e951345f17551eac2e", "organizations_url": "https://api.github.com/users/sausman/orgs", "url": "https://api.github.com/users/sausman", "gists_url": "https://api.github.com/users/sausman/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/03bcc4174eb7d5e951345f17551eac2e?d=https%3A%2F%2Fidenticons.github.com%2Fe2d8652441a60971c8af20d74e3598e7.png", "id": 309638, "events_url": "https://api.github.com/users/sausman/events{/privacy}", "login": "sausman", "received_events_url": "https://api.github.com/users/sausman/received_events", "followers_url": "https://api.github.com/users/sausman/followers"}, "body": "Thanks for the clarification.\n\nThe new test passes when conditional fragment caching works, but when it is not I get an error instead of 2 failed assertions:\n\n```\n1) Error:\ntest_conditional_fragment_caching(FragmentCachingTest):\nNoMethodError: undefined method `<<' for nil:NilClass\n    /Users/sausman/github/rails/actionpack/lib/action_view/helpers/text_helper.rb:52:in `concat'\n    /Users/sausman/github/rails/actionpack/lib/action_view/helpers/text_helper.rb:56:in `safe_concat'\n    /Users/sausman/github/rails/actionpack/lib/action_view/helpers/cache_helper.rb:35:in `cache'\n    /Users/sausman/github/rails/actionpack/test/controller/caching_test.rb:857:in `test_conditional_fragment_caching'\n    /Users/sausman/.rvm/gems/ruby-1.9.3-p0/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:28:in `run'\n    /Users/sausman/github/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:37:in `block in run'\n    /Users/sausman/github/rails/activesupport/lib/active_support/callbacks.rb:377:in `_run_callbacks_70326160161660'\n    /Users/sausman/github/rails/activesupport/lib/active_support/callbacks.rb:75:in `run_callbacks'\n    /Users/sausman/github/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:36:in `run'\n```\n\nI think `fragment_for` is returning nil when called within `cache`, but I wasn't able to find out why.", "_id": {"$oid": "523818cbbd3543c15100e0de"}, "html_url": "https://github.com/rails/rails/pull/5396#issuecomment-6079799"}
