{"updated_at": "2011-05-06T21:20:38Z", "repo": "rails", "created_at": "2011-05-06T21:20:38Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/1113683", "id": 1113683, "issue_url": "https://api.github.com/repos/rails/rails/issues/423", "issue_id": 423, "user": {"repos_url": "https://api.github.com/users/josevalim/repos", "type": "User", "html_url": "https://github.com/josevalim", "starred_url": "https://api.github.com/users/josevalim/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/josevalim/subscriptions", "following_url": "https://api.github.com/users/josevalim/following{/other_user}", "gravatar_id": "e837f6b7fd146ab16ed3d663476c063e", "organizations_url": "https://api.github.com/users/josevalim/orgs", "url": "https://api.github.com/users/josevalim", "gists_url": "https://api.github.com/users/josevalim/gists{/gist_id}", "avatar_url": "https://1.gravatar.com/avatar/e837f6b7fd146ab16ed3d663476c063e?d=https%3A%2F%2Fidenticons.github.com%2Fe20b21ae6508f22fc189c60a0880d0b8.png", "id": 9582, "events_url": "https://api.github.com/users/josevalim/events{/privacy}", "login": "josevalim", "received_events_url": "https://api.github.com/users/josevalim/received_events", "followers_url": "https://api.github.com/users/josevalim/followers"}, "body": "I have applied but had to revert those changes because tests did not pass. It seems Github do not allow me to reopen the issue, @richardiux could please open a new issue and point to this one?", "_id": {"$oid": "52386077bd3543c15101226e"}, "html_url": "https://github.com/rails/rails/pull/423#issuecomment-1113683"}
