{"body": "Branch updated! I didn't realize that rescue as control flow was against rails code style, thanks for pinpointing the issue for me.", "url": "https://api.github.com/repos/rails/rails/issues/comments/12723554", "created_at": "2013-01-25T22:16:59Z", "html_url": "https://github.com/rails/rails/pull/9041#issuecomment-12723554", "updated_at": "2013-01-25T22:16:59Z", "repo": "rails", "issue_id": 9041, "user": {"following_url": "https://api.github.com/users/sodabrew/following{/other_user}", "events_url": "https://api.github.com/users/sodabrew/events{/privacy}", "organizations_url": "https://api.github.com/users/sodabrew/orgs", "url": "https://api.github.com/users/sodabrew", "gists_url": "https://api.github.com/users/sodabrew/gists{/gist_id}", "html_url": "https://github.com/sodabrew", "subscriptions_url": "https://api.github.com/users/sodabrew/subscriptions", "avatar_url": "https://0.gravatar.com/avatar/daa42e1741f84c74ec3e6160ea6e5e11?d=https%3A%2F%2Fidenticons.github.com%2F44ccfe397ecb78a8dc09d6e524c1322d.png", "repos_url": "https://api.github.com/users/sodabrew/repos", "received_events_url": "https://api.github.com/users/sodabrew/received_events", "gravatar_id": "daa42e1741f84c74ec3e6160ea6e5e11", "starred_url": "https://api.github.com/users/sodabrew/starred{/owner}{/repo}", "login": "sodabrew", "type": "User", "id": 39406, "followers_url": "https://api.github.com/users/sodabrew/followers"}, "owner": "rails", "_id": {"$oid": "523d5ca6bd354364b9006228"}, "id": 12723554, "issue_url": "https://api.github.com/repos/rails/rails/issues/9041"}
